on: [push]

jobs:
  mirror_with_sftp:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SFTP mirror
        uses: verbindingsfout/sftp-mirror@v1.6
        with:
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }} # optional, default is 22
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local: # optional, default is ./
            remote: ${{ secrets.FTP_REMOTE_DIR }} # optional, default is ./
